#version 430

uniform writeonly image2D img;
uniform float time;

layout (local_size_x = 16, local_size_y = 16) in;
void main()
{
	ivec2 loc = ivec2(gl_GlobalInvocationID.xy);
	vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

	if( (loc.x / 16 + loc.y / 16) % 2 == 1 ) {
		color.r = sin(time) * 0.5 + 0.5;
		color.g = cos(time) * 0.5 + 0.5;
		color.b = sin(time) * cos(time) * 0.5 + 0.5;
	}

	imageStore(img, loc, color);
}
